from mcp.server.fastmcp import FastMCP, Context
from mcp.types import SamplingMessage, TextContent


#stateless_http is by default False so no need to write it
mcp = FastMCP(name="Sampling tutorial", stateless_http=False)

@mcp.tool()
async def story_telling(ctx: Context, topic: str) -> str:
     """
    Creates a short story by asking the client to generate it via sampling.

    Args:
        ctx: The MCP Context, used to communicate with the client.
        topic: The topic for the story.

    Returns:
        The story generated by the client's LLM.
    """
      
     
